name: Build and Push Docker Image
run-name: PlotTracker Build ran by ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build docker images from compose
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1
      with:
        version: latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker images
      run: docker-compose build --push

    - name: Cleanup secrets
      if: always()
      run: docker logout
    
  deploy:
    name: Deploy docker images from compose
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ vars.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Create docker compose config
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        cat docker-compose.yml | envsubst > docker-compose-secret.yml

    - name: Copy docker compose config
      run: scp docker-compose-secret.yml ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:/opt/PlotTracker/docker-compose.yml

    - name: Deploy
      run: ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "cd /opt/PlotTracker && docker-compose pull && docker-compose up -d && exit"

    - name: Cleanup secrets
      if: always()
      run: rm -rf ~/.ssh docker-compose-secret.yml
